import { promises as fs } from 'fs'
import path from 'path'

export interface Enrichment {
  videoId: string
  summary: string
  keyThemes: string[]
  keyQuotes: string[]
  careerInsights: string[]
  suggestedQuestions: string[]
  generatedAt: string
}

const ENRICHMENTS_DIR = path.join(process.cwd(), 'public', 'data', 'enrichments')

export async function getEnrichment(videoId: string): Promise<Enrichment | null> {
  // 1. Try Vercel KV if available
  if (process.env.KV_REST_API_URL && process.env.KV_REST_API_TOKEN) {
    try {
      const res = await fetch(
        `${process.env.KV_REST_API_URL}/get/enrichment:${videoId}`,
        {
          headers: { Authorization: `Bearer ${process.env.KV_REST_API_TOKEN}` },
          next: { revalidate: 86400 },
        },
      )
      if (res.ok) {
        const { result } = await res.json()
        if (result) return JSON.parse(result) as Enrichment
      }
    } catch {
      // fall through to file fallback
    }
  }

  // 2. Fall back to static JSON file generated by scripts/enrich-all.ts
  try {
    const filePath = path.join(ENRICHMENTS_DIR, `${videoId}.json`)
    const raw = await fs.readFile(filePath, 'utf-8')
    return JSON.parse(raw) as Enrichment
  } catch {
    return null
  }
}

export async function saveEnrichment(enrichment: Enrichment): Promise<void> {
  // 1. Persist to Vercel KV if available
  if (process.env.KV_REST_API_URL && process.env.KV_REST_API_TOKEN) {
    await fetch(
      `${process.env.KV_REST_API_URL}/set/enrichment:${enrichment.videoId}`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${process.env.KV_REST_API_TOKEN}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ value: JSON.stringify(enrichment) }),
      },
    )
  }

  // 2. Always write a local JSON file as the canonical fallback
  try {
    await fs.mkdir(ENRICHMENTS_DIR, { recursive: true })
    await fs.writeFile(
      path.join(ENRICHMENTS_DIR, `${enrichment.videoId}.json`),
      JSON.stringify(enrichment, null, 2),
      'utf-8',
    )
  } catch {
    // Not critical if running in a read-only deployment
  }
}
